(cl:defpackage exercise_skill-msg
  (:use )
  (:export
   "<EXERCISEACTION>"
   "EXERCISEACTION"
   "<EXERCISEACTIONFEEDBACK>"
   "EXERCISEACTIONFEEDBACK"
   "<EXERCISEACTIONGOAL>"
   "EXERCISEACTIONGOAL"
   "<EXERCISEACTIONRESULT>"
   "EXERCISEACTIONRESULT"
   "<EXERCISEFEEDBACK>"
   "EXERCISEFEEDBACK"
   "<EXERCISEGOAL>"
   "EXERCISEGOAL"
   "<EXERCISERESULT>"
   "EXERCISERESULT"
  ))

