; Auto-generated. Do not edit!


(cl:in-package exercise_skill-msg)


;//! \htmlinclude ExerciseResult.msg.html

(cl:defclass <ExerciseResult> (roslisp-msg-protocol:ros-message)
  ((skill_result
    :reader skill_result
    :initarg :skill_result
    :type cl:fixnum
    :initform 0))
)

(cl:defclass ExerciseResult (<ExerciseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExerciseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExerciseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name exercise_skill-msg:<ExerciseResult> is deprecated: use exercise_skill-msg:ExerciseResult instead.")))

(cl:ensure-generic-function 'skill_result-val :lambda-list '(m))
(cl:defmethod skill_result-val ((m <ExerciseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader exercise_skill-msg:skill_result-val is deprecated.  Use exercise_skill-msg:skill_result instead.")
  (skill_result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<ExerciseResult>)))
    "Constants for message type '<ExerciseResult>"
  '((:ERROR . -1)
    (:SUCCESS . 0)
    (:FAIL . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'ExerciseResult)))
    "Constants for message type 'ExerciseResult"
  '((:ERROR . -1)
    (:SUCCESS . 0)
    (:FAIL . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExerciseResult>) ostream)
  "Serializes a message object of type '<ExerciseResult>"
  (cl:let* ((signed (cl:slot-value msg 'skill_result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExerciseResult>) istream)
  "Deserializes a message object of type '<ExerciseResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'skill_result) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExerciseResult>)))
  "Returns string type for a message object of type '<ExerciseResult>"
  "exercise_skill/ExerciseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExerciseResult)))
  "Returns string type for a message object of type 'ExerciseResult"
  "exercise_skill/ExerciseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExerciseResult>)))
  "Returns md5sum for a message object of type '<ExerciseResult>"
  "4e5dc85de4836ff949b7a939d7ae0b33")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExerciseResult)))
  "Returns md5sum for a message object of type 'ExerciseResult"
  "4e5dc85de4836ff949b7a939d7ae0b33")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExerciseResult>)))
  "Returns full string definition for message of type '<ExerciseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 ERROR = -1~%int8 SUCCESS = 0~%int8 FAIL = 1~%int8 skill_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExerciseResult)))
  "Returns full string definition for message of type 'ExerciseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 ERROR = -1~%int8 SUCCESS = 0~%int8 FAIL = 1~%int8 skill_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExerciseResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExerciseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExerciseResult
    (cl:cons ':skill_result (skill_result msg))
))
