// Auto-generated. Do not edit!

// (in-package etts_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class UtteranceResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.consequence = null;
    }
    else {
      if (initObj.hasOwnProperty('consequence')) {
        this.consequence = initObj.consequence
      }
      else {
        this.consequence = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type UtteranceResult
    // Serialize message field [consequence]
    bufferOffset = _serializer.int32(obj.consequence, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type UtteranceResult
    let len;
    let data = new UtteranceResult(null);
    // Deserialize message field [consequence]
    data.consequence = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'etts_msgs/UtteranceResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e32be056f2465f39e2f2bb3a11cab968';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Result of the action, only is sended once
    int32 consequence
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new UtteranceResult(null);
    if (msg.consequence !== undefined) {
      resolved.consequence = msg.consequence;
    }
    else {
      resolved.consequence = 0
    }

    return resolved;
    }
};

module.exports = UtteranceResult;
