// Generated by gencpp from file etts_msgs/UtteranceFeedback.msg
// DO NOT EDIT!


#ifndef ETTS_MSGS_MESSAGE_UTTERANCEFEEDBACK_H
#define ETTS_MSGS_MESSAGE_UTTERANCEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace etts_msgs
{
template <class ContainerAllocator>
struct UtteranceFeedback_
{
  typedef UtteranceFeedback_<ContainerAllocator> Type;

  UtteranceFeedback_()
    : utteranceReceived(false)  {
    }
  UtteranceFeedback_(const ContainerAllocator& _alloc)
    : utteranceReceived(false)  {
  (void)_alloc;
    }



   typedef uint8_t _utteranceReceived_type;
  _utteranceReceived_type utteranceReceived;





  typedef boost::shared_ptr< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct UtteranceFeedback_

typedef ::etts_msgs::UtteranceFeedback_<std::allocator<void> > UtteranceFeedback;

typedef boost::shared_ptr< ::etts_msgs::UtteranceFeedback > UtteranceFeedbackPtr;
typedef boost::shared_ptr< ::etts_msgs::UtteranceFeedback const> UtteranceFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etts_msgs::UtteranceFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'etts_msgs': ['/home/haobing/catkin_ws/src/etts_msgs/msg', '/home/haobing/catkin_ws/devel/share/etts_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f93db1cfa40fa25f3ce813f87e25315d";
  }

  static const char* value(const ::etts_msgs::UtteranceFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf93db1cfa40fa25fULL;
  static const uint64_t static_value2 = 0x3ce813f87e25315dULL;
};

template<class ContainerAllocator>
struct DataType< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etts_msgs/UtteranceFeedback";
  }

  static const char* value(const ::etts_msgs::UtteranceFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Feedback about the progress of the action\n\
bool utteranceReceived\n\
\n\
";
  }

  static const char* value(const ::etts_msgs::UtteranceFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.utteranceReceived);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UtteranceFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::etts_msgs::UtteranceFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etts_msgs::UtteranceFeedback_<ContainerAllocator>& v)
  {
    s << indent << "utteranceReceived: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.utteranceReceived);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETTS_MSGS_MESSAGE_UTTERANCEFEEDBACK_H
