// Generated by gencpp from file etts_msgs/UtteranceResult.msg
// DO NOT EDIT!


#ifndef ETTS_MSGS_MESSAGE_UTTERANCERESULT_H
#define ETTS_MSGS_MESSAGE_UTTERANCERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace etts_msgs
{
template <class ContainerAllocator>
struct UtteranceResult_
{
  typedef UtteranceResult_<ContainerAllocator> Type;

  UtteranceResult_()
    : consequence(0)  {
    }
  UtteranceResult_(const ContainerAllocator& _alloc)
    : consequence(0)  {
  (void)_alloc;
    }



   typedef int32_t _consequence_type;
  _consequence_type consequence;





  typedef boost::shared_ptr< ::etts_msgs::UtteranceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etts_msgs::UtteranceResult_<ContainerAllocator> const> ConstPtr;

}; // struct UtteranceResult_

typedef ::etts_msgs::UtteranceResult_<std::allocator<void> > UtteranceResult;

typedef boost::shared_ptr< ::etts_msgs::UtteranceResult > UtteranceResultPtr;
typedef boost::shared_ptr< ::etts_msgs::UtteranceResult const> UtteranceResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etts_msgs::UtteranceResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etts_msgs::UtteranceResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'etts_msgs': ['/home/haobing/catkin_ws/src/etts_msgs/msg', '/home/haobing/catkin_ws/devel/share/etts_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etts_msgs::UtteranceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etts_msgs::UtteranceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etts_msgs::UtteranceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etts_msgs::UtteranceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etts_msgs::UtteranceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etts_msgs::UtteranceResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etts_msgs::UtteranceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e32be056f2465f39e2f2bb3a11cab968";
  }

  static const char* value(const ::etts_msgs::UtteranceResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe32be056f2465f39ULL;
  static const uint64_t static_value2 = 0xe2f2bb3a11cab968ULL;
};

template<class ContainerAllocator>
struct DataType< ::etts_msgs::UtteranceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etts_msgs/UtteranceResult";
  }

  static const char* value(const ::etts_msgs::UtteranceResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etts_msgs::UtteranceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Result of the action, only is sended once\n\
int32 consequence\n\
";
  }

  static const char* value(const ::etts_msgs::UtteranceResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::etts_msgs::UtteranceResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.consequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UtteranceResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::etts_msgs::UtteranceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etts_msgs::UtteranceResult_<ContainerAllocator>& v)
  {
    s << indent << "consequence: ";
    Printer<int32_t>::stream(s, indent + "  ", v.consequence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETTS_MSGS_MESSAGE_UTTERANCERESULT_H
