// Generated by gencpp from file android_skill/AndroidFeedback.msg
// DO NOT EDIT!


#ifndef ANDROID_SKILL_MESSAGE_ANDROIDFEEDBACK_H
#define ANDROID_SKILL_MESSAGE_ANDROIDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace android_skill
{
template <class ContainerAllocator>
struct AndroidFeedback_
{
  typedef AndroidFeedback_<ContainerAllocator> Type;

  AndroidFeedback_()
    : app_status()
    , percentage_completed(0)
    , engagement(false)  {
    }
  AndroidFeedback_(const ContainerAllocator& _alloc)
    : app_status(_alloc)
    , percentage_completed(0)
    , engagement(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _app_status_type;
  _app_status_type app_status;

   typedef uint8_t _percentage_completed_type;
  _percentage_completed_type percentage_completed;

   typedef uint8_t _engagement_type;
  _engagement_type engagement;





  typedef boost::shared_ptr< ::android_skill::AndroidFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::android_skill::AndroidFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AndroidFeedback_

typedef ::android_skill::AndroidFeedback_<std::allocator<void> > AndroidFeedback;

typedef boost::shared_ptr< ::android_skill::AndroidFeedback > AndroidFeedbackPtr;
typedef boost::shared_ptr< ::android_skill::AndroidFeedback const> AndroidFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::android_skill::AndroidFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::android_skill::AndroidFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace android_skill

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'interaction_msgs': ['/home/haobing/catkin_ws/src/interaction_msgs/msg'], 'android_skill': ['/home/haobing/catkin_ws/devel/share/android_skill/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'common_msgs': ['/home/haobing/catkin_ws/src/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::android_skill::AndroidFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::android_skill::AndroidFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::android_skill::AndroidFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::android_skill::AndroidFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::android_skill::AndroidFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::android_skill::AndroidFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::android_skill::AndroidFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dae6119bde17e0325e6052cc5fd30b90";
  }

  static const char* value(const ::android_skill::AndroidFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdae6119bde17e032ULL;
  static const uint64_t static_value2 = 0x5e6052cc5fd30b90ULL;
};

template<class ContainerAllocator>
struct DataType< ::android_skill::AndroidFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "android_skill/AndroidFeedback";
  }

  static const char* value(const ::android_skill::AndroidFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::android_skill::AndroidFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
string app_status\n\
uint8 percentage_completed\n\
bool engagement\n\
";
  }

  static const char* value(const ::android_skill::AndroidFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::android_skill::AndroidFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.app_status);
      stream.next(m.percentage_completed);
      stream.next(m.engagement);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AndroidFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::android_skill::AndroidFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::android_skill::AndroidFeedback_<ContainerAllocator>& v)
  {
    s << indent << "app_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.app_status);
    s << indent << "percentage_completed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.percentage_completed);
    s << indent << "engagement: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.engagement);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANDROID_SKILL_MESSAGE_ANDROIDFEEDBACK_H
