(cl:defpackage hand_gesture_skill-msg
  (:use )
  (:export
   "<HANDGESTUREACTION>"
   "HANDGESTUREACTION"
   "<HANDGESTUREACTIONFEEDBACK>"
   "HANDGESTUREACTIONFEEDBACK"
   "<HANDGESTUREACTIONGOAL>"
   "HANDGESTUREACTIONGOAL"
   "<HANDGESTUREACTIONRESULT>"
   "HANDGESTUREACTIONRESULT"
   "<HANDGESTUREFEEDBACK>"
   "HANDGESTUREFEEDBACK"
   "<HANDGESTUREGOAL>"
   "HANDGESTUREGOAL"
   "<HANDGESTURERESULT>"
   "HANDGESTURERESULT"
  ))

