; Auto-generated. Do not edit!


(cl:in-package hand_gesture_skill-msg)


;//! \htmlinclude HandGestureResult.msg.html

(cl:defclass <HandGestureResult> (roslisp-msg-protocol:ros-message)
  ((end_minigame
    :reader end_minigame
    :initarg :end_minigame
    :type cl:integer
    :initform 0))
)

(cl:defclass HandGestureResult (<HandGestureResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HandGestureResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HandGestureResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hand_gesture_skill-msg:<HandGestureResult> is deprecated: use hand_gesture_skill-msg:HandGestureResult instead.")))

(cl:ensure-generic-function 'end_minigame-val :lambda-list '(m))
(cl:defmethod end_minigame-val ((m <HandGestureResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hand_gesture_skill-msg:end_minigame-val is deprecated.  Use hand_gesture_skill-msg:end_minigame instead.")
  (end_minigame m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HandGestureResult>) ostream)
  "Serializes a message object of type '<HandGestureResult>"
  (cl:let* ((signed (cl:slot-value msg 'end_minigame)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HandGestureResult>) istream)
  "Deserializes a message object of type '<HandGestureResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'end_minigame) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HandGestureResult>)))
  "Returns string type for a message object of type '<HandGestureResult>"
  "hand_gesture_skill/HandGestureResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HandGestureResult)))
  "Returns string type for a message object of type 'HandGestureResult"
  "hand_gesture_skill/HandGestureResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HandGestureResult>)))
  "Returns md5sum for a message object of type '<HandGestureResult>"
  "712ca2f7654cbc2a2a7b96f504256e1f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HandGestureResult)))
  "Returns md5sum for a message object of type 'HandGestureResult"
  "712ca2f7654cbc2a2a7b96f504256e1f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HandGestureResult>)))
  "Returns full string definition for message of type '<HandGestureResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%int32 end_minigame~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HandGestureResult)))
  "Returns full string definition for message of type 'HandGestureResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%int32 end_minigame~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HandGestureResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HandGestureResult>))
  "Converts a ROS message object to a list"
  (cl:list 'HandGestureResult
    (cl:cons ':end_minigame (end_minigame msg))
))
