; Auto-generated. Do not edit!


(cl:in-package hand_gesture_skill-msg)


;//! \htmlinclude HandGestureFeedback.msg.html

(cl:defclass <HandGestureFeedback> (roslisp-msg-protocol:ros-message)
  ((questions_completed
    :reader questions_completed
    :initarg :questions_completed
    :type cl:integer
    :initform 0))
)

(cl:defclass HandGestureFeedback (<HandGestureFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HandGestureFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HandGestureFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hand_gesture_skill-msg:<HandGestureFeedback> is deprecated: use hand_gesture_skill-msg:HandGestureFeedback instead.")))

(cl:ensure-generic-function 'questions_completed-val :lambda-list '(m))
(cl:defmethod questions_completed-val ((m <HandGestureFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hand_gesture_skill-msg:questions_completed-val is deprecated.  Use hand_gesture_skill-msg:questions_completed instead.")
  (questions_completed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HandGestureFeedback>) ostream)
  "Serializes a message object of type '<HandGestureFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'questions_completed)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HandGestureFeedback>) istream)
  "Deserializes a message object of type '<HandGestureFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'questions_completed) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HandGestureFeedback>)))
  "Returns string type for a message object of type '<HandGestureFeedback>"
  "hand_gesture_skill/HandGestureFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HandGestureFeedback)))
  "Returns string type for a message object of type 'HandGestureFeedback"
  "hand_gesture_skill/HandGestureFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HandGestureFeedback>)))
  "Returns md5sum for a message object of type '<HandGestureFeedback>"
  "c759c794305866da6e45b34ea3a27ff4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HandGestureFeedback)))
  "Returns md5sum for a message object of type 'HandGestureFeedback"
  "c759c794305866da6e45b34ea3a27ff4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HandGestureFeedback>)))
  "Returns full string definition for message of type '<HandGestureFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%int32 questions_completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HandGestureFeedback)))
  "Returns full string definition for message of type 'HandGestureFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%int32 questions_completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HandGestureFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HandGestureFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'HandGestureFeedback
    (cl:cons ':questions_completed (questions_completed msg))
))
