(cl:defpackage android_skill-msg
  (:use )
  (:export
   "<ANDROIDACTION>"
   "ANDROIDACTION"
   "<ANDROIDACTIONFEEDBACK>"
   "ANDROIDACTIONFEEDBACK"
   "<ANDROIDACTIONGOAL>"
   "ANDROIDACTIONGOAL"
   "<ANDROIDACTIONRESULT>"
   "ANDROIDACTIONRESULT"
   "<ANDROIDFEEDBACK>"
   "ANDROIDFEEDBACK"
   "<ANDROIDGOAL>"
   "ANDROIDGOAL"
   "<ANDROIDRESULT>"
   "ANDROIDRESULT"
  ))

