; Auto-generated. Do not edit!


(cl:in-package android_skill-msg)


;//! \htmlinclude AndroidFeedback.msg.html

(cl:defclass <AndroidFeedback> (roslisp-msg-protocol:ros-message)
  ((app_status
    :reader app_status
    :initarg :app_status
    :type cl:string
    :initform "")
   (percentage_completed
    :reader percentage_completed
    :initarg :percentage_completed
    :type cl:fixnum
    :initform 0)
   (engagement
    :reader engagement
    :initarg :engagement
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass AndroidFeedback (<AndroidFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AndroidFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AndroidFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name android_skill-msg:<AndroidFeedback> is deprecated: use android_skill-msg:AndroidFeedback instead.")))

(cl:ensure-generic-function 'app_status-val :lambda-list '(m))
(cl:defmethod app_status-val ((m <AndroidFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader android_skill-msg:app_status-val is deprecated.  Use android_skill-msg:app_status instead.")
  (app_status m))

(cl:ensure-generic-function 'percentage_completed-val :lambda-list '(m))
(cl:defmethod percentage_completed-val ((m <AndroidFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader android_skill-msg:percentage_completed-val is deprecated.  Use android_skill-msg:percentage_completed instead.")
  (percentage_completed m))

(cl:ensure-generic-function 'engagement-val :lambda-list '(m))
(cl:defmethod engagement-val ((m <AndroidFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader android_skill-msg:engagement-val is deprecated.  Use android_skill-msg:engagement instead.")
  (engagement m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AndroidFeedback>) ostream)
  "Serializes a message object of type '<AndroidFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'app_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'app_status))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'percentage_completed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'engagement) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AndroidFeedback>) istream)
  "Deserializes a message object of type '<AndroidFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'app_status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'app_status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'percentage_completed)) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'engagement) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AndroidFeedback>)))
  "Returns string type for a message object of type '<AndroidFeedback>"
  "android_skill/AndroidFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AndroidFeedback)))
  "Returns string type for a message object of type 'AndroidFeedback"
  "android_skill/AndroidFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AndroidFeedback>)))
  "Returns md5sum for a message object of type '<AndroidFeedback>"
  "dae6119bde17e0325e6052cc5fd30b90")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AndroidFeedback)))
  "Returns md5sum for a message object of type 'AndroidFeedback"
  "dae6119bde17e0325e6052cc5fd30b90")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AndroidFeedback>)))
  "Returns full string definition for message of type '<AndroidFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string app_status~%uint8 percentage_completed~%bool engagement~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AndroidFeedback)))
  "Returns full string definition for message of type 'AndroidFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string app_status~%uint8 percentage_completed~%bool engagement~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AndroidFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'app_status))
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AndroidFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AndroidFeedback
    (cl:cons ':app_status (app_status msg))
    (cl:cons ':percentage_completed (percentage_completed msg))
    (cl:cons ':engagement (engagement msg))
))
