; Auto-generated. Do not edit!


(cl:in-package android_skill-msg)


;//! \htmlinclude AndroidResult.msg.html

(cl:defclass <AndroidResult> (roslisp-msg-protocol:ros-message)
  ((skill_result
    :reader skill_result
    :initarg :skill_result
    :type cl:fixnum
    :initform 0))
)

(cl:defclass AndroidResult (<AndroidResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AndroidResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AndroidResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name android_skill-msg:<AndroidResult> is deprecated: use android_skill-msg:AndroidResult instead.")))

(cl:ensure-generic-function 'skill_result-val :lambda-list '(m))
(cl:defmethod skill_result-val ((m <AndroidResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader android_skill-msg:skill_result-val is deprecated.  Use android_skill-msg:skill_result instead.")
  (skill_result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<AndroidResult>)))
    "Constants for message type '<AndroidResult>"
  '((:ERROR . -1)
    (:SUCCESS . 0)
    (:FAIL . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'AndroidResult)))
    "Constants for message type 'AndroidResult"
  '((:ERROR . -1)
    (:SUCCESS . 0)
    (:FAIL . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AndroidResult>) ostream)
  "Serializes a message object of type '<AndroidResult>"
  (cl:let* ((signed (cl:slot-value msg 'skill_result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AndroidResult>) istream)
  "Deserializes a message object of type '<AndroidResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'skill_result) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AndroidResult>)))
  "Returns string type for a message object of type '<AndroidResult>"
  "android_skill/AndroidResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AndroidResult)))
  "Returns string type for a message object of type 'AndroidResult"
  "android_skill/AndroidResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AndroidResult>)))
  "Returns md5sum for a message object of type '<AndroidResult>"
  "4e5dc85de4836ff949b7a939d7ae0b33")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AndroidResult)))
  "Returns md5sum for a message object of type 'AndroidResult"
  "4e5dc85de4836ff949b7a939d7ae0b33")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AndroidResult>)))
  "Returns full string definition for message of type '<AndroidResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int8 ERROR = -1~%int8 SUCCESS = 0~%int8 FAIL = 1~%int8 skill_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AndroidResult)))
  "Returns full string definition for message of type 'AndroidResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int8 ERROR = -1~%int8 SUCCESS = 0~%int8 FAIL = 1~%int8 skill_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AndroidResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AndroidResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AndroidResult
    (cl:cons ':skill_result (skill_result msg))
))
