(cl:defpackage etts_msgs-msg
  (:use )
  (:export
   "<UTTERANCE>"
   "UTTERANCE"
   "<UTTERANCEACTION>"
   "UTTERANCEACTION"
   "<UTTERANCEACTIONFEEDBACK>"
   "UTTERANCEACTIONFEEDBACK"
   "<UTTERANCEACTIONGOAL>"
   "UTTERANCEACTIONGOAL"
   "<UTTERANCEACTIONRESULT>"
   "UTTERANCEACTIONRESULT"
   "<UTTERANCEFEEDBACK>"
   "UTTERANCEFEEDBACK"
   "<UTTERANCEGOAL>"
   "UTTERANCEGOAL"
   "<UTTERANCERESULT>"
   "UTTERANCERESULT"
  ))

