; Auto-generated. Do not edit!


(cl:in-package etts_msgs-msg)


;//! \htmlinclude UtteranceResult.msg.html

(cl:defclass <UtteranceResult> (roslisp-msg-protocol:ros-message)
  ((consequence
    :reader consequence
    :initarg :consequence
    :type cl:integer
    :initform 0))
)

(cl:defclass UtteranceResult (<UtteranceResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <UtteranceResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'UtteranceResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name etts_msgs-msg:<UtteranceResult> is deprecated: use etts_msgs-msg:UtteranceResult instead.")))

(cl:ensure-generic-function 'consequence-val :lambda-list '(m))
(cl:defmethod consequence-val ((m <UtteranceResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader etts_msgs-msg:consequence-val is deprecated.  Use etts_msgs-msg:consequence instead.")
  (consequence m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <UtteranceResult>) ostream)
  "Serializes a message object of type '<UtteranceResult>"
  (cl:let* ((signed (cl:slot-value msg 'consequence)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <UtteranceResult>) istream)
  "Deserializes a message object of type '<UtteranceResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'consequence) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<UtteranceResult>)))
  "Returns string type for a message object of type '<UtteranceResult>"
  "etts_msgs/UtteranceResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'UtteranceResult)))
  "Returns string type for a message object of type 'UtteranceResult"
  "etts_msgs/UtteranceResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<UtteranceResult>)))
  "Returns md5sum for a message object of type '<UtteranceResult>"
  "e32be056f2465f39e2f2bb3a11cab968")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'UtteranceResult)))
  "Returns md5sum for a message object of type 'UtteranceResult"
  "e32be056f2465f39e2f2bb3a11cab968")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<UtteranceResult>)))
  "Returns full string definition for message of type '<UtteranceResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result of the action, only is sended once~%int32 consequence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'UtteranceResult)))
  "Returns full string definition for message of type 'UtteranceResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result of the action, only is sended once~%int32 consequence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <UtteranceResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <UtteranceResult>))
  "Converts a ROS message object to a list"
  (cl:list 'UtteranceResult
    (cl:cons ':consequence (consequence msg))
))
