// Generated by gencpp from file interaction_msgs/ExpressionStatus.msg
// DO NOT EDIT!


#ifndef INTERACTION_MSGS_MESSAGE_EXPRESSIONSTATUS_H
#define INTERACTION_MSGS_MESSAGE_EXPRESSIONSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace interaction_msgs
{
template <class ContainerAllocator>
struct ExpressionStatus_
{
  typedef ExpressionStatus_<ContainerAllocator> Type;

  ExpressionStatus_()
    : header()
    , name()
    , id()
    , emitter()
    , result()
    , error()  {
    }
  ExpressionStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , id(_alloc)
    , emitter(_alloc)
    , result(_alloc)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _emitter_type;
  _emitter_type emitter;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ExpressionStatus_

typedef ::interaction_msgs::ExpressionStatus_<std::allocator<void> > ExpressionStatus;

typedef boost::shared_ptr< ::interaction_msgs::ExpressionStatus > ExpressionStatusPtr;
typedef boost::shared_ptr< ::interaction_msgs::ExpressionStatus const> ExpressionStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interaction_msgs::ExpressionStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace interaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'interaction_msgs': ['/home/haobing/catkin_ws/src/interaction_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'common_msgs': ['/home/haobing/catkin_ws/src/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76f460b31d117741daf9ae0482e0da70";
  }

  static const char* value(const ::interaction_msgs::ExpressionStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76f460b31d117741ULL;
  static const uint64_t static_value2 = 0xdaf9ae0482e0da70ULL;
};

template<class ContainerAllocator>
struct DataType< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interaction_msgs/ExpressionStatus";
  }

  static const char* value(const ::interaction_msgs::ExpressionStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#use standard header\n\
Header header\n\
\n\
#name of the expression just ended\n\
string name\n\
\n\
#unique identifier for the expression\n\
string id\n\
\n\
string emitter\n\
\n\
#expresion executed successfully?\n\
string result\n\
\n\
#description of the error in case of a non-successfully completed expression\n\
string error\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::interaction_msgs::ExpressionStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.id);
      stream.next(m.emitter);
      stream.next(m.result);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExpressionStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interaction_msgs::ExpressionStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interaction_msgs::ExpressionStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "emitter: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.emitter);
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERACTION_MSGS_MESSAGE_EXPRESSIONSTATUS_H
