// Generated by gencpp from file hand_gesture_skill/HandGestureResult.msg
// DO NOT EDIT!


#ifndef HAND_GESTURE_SKILL_MESSAGE_HANDGESTURERESULT_H
#define HAND_GESTURE_SKILL_MESSAGE_HANDGESTURERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_gesture_skill
{
template <class ContainerAllocator>
struct HandGestureResult_
{
  typedef HandGestureResult_<ContainerAllocator> Type;

  HandGestureResult_()
    : end_minigame(0)  {
    }
  HandGestureResult_(const ContainerAllocator& _alloc)
    : end_minigame(0)  {
  (void)_alloc;
    }



   typedef int32_t _end_minigame_type;
  _end_minigame_type end_minigame;





  typedef boost::shared_ptr< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> const> ConstPtr;

}; // struct HandGestureResult_

typedef ::hand_gesture_skill::HandGestureResult_<std::allocator<void> > HandGestureResult;

typedef boost::shared_ptr< ::hand_gesture_skill::HandGestureResult > HandGestureResultPtr;
typedef boost::shared_ptr< ::hand_gesture_skill::HandGestureResult const> HandGestureResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_gesture_skill

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'interaction_msgs': ['/home/haobing/catkin_ws/src/interaction_msgs/msg'], 'hand_gesture_skill': ['/home/haobing/catkin_ws/devel/share/hand_gesture_skill/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hand_gesture_msgs': ['/home/haobing/catkin_ws/src/hand_gesture_msgs/msg'], 'common_msgs': ['/home/haobing/catkin_ws/src/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "712ca2f7654cbc2a2a7b96f504256e1f";
  }

  static const char* value(const ::hand_gesture_skill::HandGestureResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x712ca2f7654cbc2aULL;
  static const uint64_t static_value2 = 0x2a7b96f504256e1fULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_gesture_skill/HandGestureResult";
  }

  static const char* value(const ::hand_gesture_skill::HandGestureResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
int32 end_minigame\n\
";
  }

  static const char* value(const ::hand_gesture_skill::HandGestureResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.end_minigame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandGestureResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_gesture_skill::HandGestureResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_gesture_skill::HandGestureResult_<ContainerAllocator>& v)
  {
    s << indent << "end_minigame: ";
    Printer<int32_t>::stream(s, indent + "  ", v.end_minigame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_GESTURE_SKILL_MESSAGE_HANDGESTURERESULT_H
