// Generated by gencpp from file hand_gesture_skill/HandGestureGoal.msg
// DO NOT EDIT!


#ifndef HAND_GESTURE_SKILL_MESSAGE_HANDGESTUREGOAL_H
#define HAND_GESTURE_SKILL_MESSAGE_HANDGESTUREGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_gesture_skill
{
template <class ContainerAllocator>
struct HandGestureGoal_
{
  typedef HandGestureGoal_<ContainerAllocator> Type;

  HandGestureGoal_()
    : num_minigame()  {
    }
  HandGestureGoal_(const ContainerAllocator& _alloc)
    : num_minigame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _num_minigame_type;
  _num_minigame_type num_minigame;





  typedef boost::shared_ptr< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> const> ConstPtr;

}; // struct HandGestureGoal_

typedef ::hand_gesture_skill::HandGestureGoal_<std::allocator<void> > HandGestureGoal;

typedef boost::shared_ptr< ::hand_gesture_skill::HandGestureGoal > HandGestureGoalPtr;
typedef boost::shared_ptr< ::hand_gesture_skill::HandGestureGoal const> HandGestureGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_gesture_skill

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'interaction_msgs': ['/home/haobing/catkin_ws/src/interaction_msgs/msg'], 'hand_gesture_skill': ['/home/haobing/catkin_ws/devel/share/hand_gesture_skill/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hand_gesture_msgs': ['/home/haobing/catkin_ws/src/hand_gesture_msgs/msg'], 'common_msgs': ['/home/haobing/catkin_ws/src/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6eb5059f69bb8d585283424a293f9480";
  }

  static const char* value(const ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6eb5059f69bb8d58ULL;
  static const uint64_t static_value2 = 0x5283424a293f9480ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_gesture_skill/HandGestureGoal";
  }

  static const char* value(const ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
string num_minigame\n\
";
  }

  static const char* value(const ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_minigame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandGestureGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_gesture_skill::HandGestureGoal_<ContainerAllocator>& v)
  {
    s << indent << "num_minigame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.num_minigame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_GESTURE_SKILL_MESSAGE_HANDGESTUREGOAL_H
