// Auto-generated. Do not edit!

// (in-package hand_gesture_skill.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class HandGestureResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.end_minigame = null;
    }
    else {
      if (initObj.hasOwnProperty('end_minigame')) {
        this.end_minigame = initObj.end_minigame
      }
      else {
        this.end_minigame = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type HandGestureResult
    // Serialize message field [end_minigame]
    bufferOffset = _serializer.int32(obj.end_minigame, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type HandGestureResult
    let len;
    let data = new HandGestureResult(null);
    // Deserialize message field [end_minigame]
    data.end_minigame = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hand_gesture_skill/HandGestureResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '712ca2f7654cbc2a2a7b96f504256e1f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    int32 end_minigame
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new HandGestureResult(null);
    if (msg.end_minigame !== undefined) {
      resolved.end_minigame = msg.end_minigame;
    }
    else {
      resolved.end_minigame = 0
    }

    return resolved;
    }
};

module.exports = HandGestureResult;
