// Auto-generated. Do not edit!

// (in-package hand_gesture_skill.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class HandGestureFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.questions_completed = null;
    }
    else {
      if (initObj.hasOwnProperty('questions_completed')) {
        this.questions_completed = initObj.questions_completed
      }
      else {
        this.questions_completed = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type HandGestureFeedback
    // Serialize message field [questions_completed]
    bufferOffset = _serializer.int32(obj.questions_completed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type HandGestureFeedback
    let len;
    let data = new HandGestureFeedback(null);
    // Deserialize message field [questions_completed]
    data.questions_completed = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hand_gesture_skill/HandGestureFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c759c794305866da6e45b34ea3a27ff4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    int32 questions_completed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new HandGestureFeedback(null);
    if (msg.questions_completed !== undefined) {
      resolved.questions_completed = msg.questions_completed;
    }
    else {
      resolved.questions_completed = 0
    }

    return resolved;
    }
};

module.exports = HandGestureFeedback;
