// Generated by gencpp from file ros_openpose/Gesture.msg
// DO NOT EDIT!


#ifndef ROS_OPENPOSE_MESSAGE_GESTURE_H
#define ROS_OPENPOSE_MESSAGE_GESTURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_openpose
{
template <class ContainerAllocator>
struct Gesture_
{
  typedef Gesture_<ContainerAllocator> Type;

  Gesture_()
    : lefthand()
    , righthand()
    , body()  {
    }
  Gesture_(const ContainerAllocator& _alloc)
    : lefthand(_alloc)
    , righthand(_alloc)
    , body(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lefthand_type;
  _lefthand_type lefthand;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _righthand_type;
  _righthand_type righthand;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _body_type;
  _body_type body;





  typedef boost::shared_ptr< ::ros_openpose::Gesture_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_openpose::Gesture_<ContainerAllocator> const> ConstPtr;

}; // struct Gesture_

typedef ::ros_openpose::Gesture_<std::allocator<void> > Gesture;

typedef boost::shared_ptr< ::ros_openpose::Gesture > GesturePtr;
typedef boost::shared_ptr< ::ros_openpose::Gesture const> GestureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_openpose::Gesture_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_openpose::Gesture_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_openpose

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_openpose': ['/home/haobing/catkin_ws/src/openpose_ros/ros_openpose/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_openpose::Gesture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_openpose::Gesture_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_openpose::Gesture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_openpose::Gesture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_openpose::Gesture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_openpose::Gesture_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_openpose::Gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd533947e2ddb7675745edef8ae88c25";
  }

  static const char* value(const ::ros_openpose::Gesture_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd533947e2ddb767ULL;
  static const uint64_t static_value2 = 0x5745edef8ae88c25ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_openpose::Gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_openpose/Gesture";
  }

  static const char* value(const ::ros_openpose::Gesture_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_openpose::Gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string lefthand\n\
string righthand\n\
string body\n\
";
  }

  static const char* value(const ::ros_openpose::Gesture_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_openpose::Gesture_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lefthand);
      stream.next(m.righthand);
      stream.next(m.body);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gesture_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_openpose::Gesture_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_openpose::Gesture_<ContainerAllocator>& v)
  {
    s << indent << "lefthand: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lefthand);
    s << indent << "righthand: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.righthand);
    s << indent << "body: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.body);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPENPOSE_MESSAGE_GESTURE_H
