// Generated by gencpp from file ros_openpose/Numperson.msg
// DO NOT EDIT!


#ifndef ROS_OPENPOSE_MESSAGE_NUMPERSON_H
#define ROS_OPENPOSE_MESSAGE_NUMPERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_openpose
{
template <class ContainerAllocator>
struct Numperson_
{
  typedef Numperson_<ContainerAllocator> Type;

  Numperson_()
    : data(0)  {
    }
  Numperson_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros_openpose::Numperson_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_openpose::Numperson_<ContainerAllocator> const> ConstPtr;

}; // struct Numperson_

typedef ::ros_openpose::Numperson_<std::allocator<void> > Numperson;

typedef boost::shared_ptr< ::ros_openpose::Numperson > NumpersonPtr;
typedef boost::shared_ptr< ::ros_openpose::Numperson const> NumpersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_openpose::Numperson_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_openpose::Numperson_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_openpose

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_openpose': ['/home/haobing/catkin_ws/src/openpose_ros/ros_openpose/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_openpose::Numperson_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_openpose::Numperson_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_openpose::Numperson_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_openpose::Numperson_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_openpose::Numperson_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_openpose::Numperson_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_openpose::Numperson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "304a39449588c7f8ce2df6e8001c5fce";
  }

  static const char* value(const ::ros_openpose::Numperson_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x304a39449588c7f8ULL;
  static const uint64_t static_value2 = 0xce2df6e8001c5fceULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_openpose::Numperson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_openpose/Numperson";
  }

  static const char* value(const ::ros_openpose::Numperson_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_openpose::Numperson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 data\n\
";
  }

  static const char* value(const ::ros_openpose::Numperson_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_openpose::Numperson_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Numperson_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_openpose::Numperson_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_openpose::Numperson_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPENPOSE_MESSAGE_NUMPERSON_H
