(cl:defpackage tutorial_skill-msg
  (:use )
  (:export
   "<TUTORIALACTION>"
   "TUTORIALACTION"
   "<TUTORIALACTIONFEEDBACK>"
   "TUTORIALACTIONFEEDBACK"
   "<TUTORIALACTIONGOAL>"
   "TUTORIALACTIONGOAL"
   "<TUTORIALACTIONRESULT>"
   "TUTORIALACTIONRESULT"
   "<TUTORIALFEEDBACK>"
   "TUTORIALFEEDBACK"
   "<TUTORIALGOAL>"
   "TUTORIALGOAL"
   "<TUTORIALRESULT>"
   "TUTORIALRESULT"
  ))

