; Auto-generated. Do not edit!


(cl:in-package tutorial_skill-msg)


;//! \htmlinclude TutorialResult.msg.html

(cl:defclass <TutorialResult> (roslisp-msg-protocol:ros-message)
  ((skill_result
    :reader skill_result
    :initarg :skill_result
    :type cl:fixnum
    :initform 0))
)

(cl:defclass TutorialResult (<TutorialResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TutorialResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TutorialResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial_skill-msg:<TutorialResult> is deprecated: use tutorial_skill-msg:TutorialResult instead.")))

(cl:ensure-generic-function 'skill_result-val :lambda-list '(m))
(cl:defmethod skill_result-val ((m <TutorialResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial_skill-msg:skill_result-val is deprecated.  Use tutorial_skill-msg:skill_result instead.")
  (skill_result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<TutorialResult>)))
    "Constants for message type '<TutorialResult>"
  '((:ERROR . -1)
    (:SUCCESS . 0)
    (:FAIL . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'TutorialResult)))
    "Constants for message type 'TutorialResult"
  '((:ERROR . -1)
    (:SUCCESS . 0)
    (:FAIL . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TutorialResult>) ostream)
  "Serializes a message object of type '<TutorialResult>"
  (cl:let* ((signed (cl:slot-value msg 'skill_result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TutorialResult>) istream)
  "Deserializes a message object of type '<TutorialResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'skill_result) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TutorialResult>)))
  "Returns string type for a message object of type '<TutorialResult>"
  "tutorial_skill/TutorialResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TutorialResult)))
  "Returns string type for a message object of type 'TutorialResult"
  "tutorial_skill/TutorialResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TutorialResult>)))
  "Returns md5sum for a message object of type '<TutorialResult>"
  "4e5dc85de4836ff949b7a939d7ae0b33")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TutorialResult)))
  "Returns md5sum for a message object of type 'TutorialResult"
  "4e5dc85de4836ff949b7a939d7ae0b33")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TutorialResult>)))
  "Returns full string definition for message of type '<TutorialResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 ERROR = -1~%int8 SUCCESS = 0~%int8 FAIL = 1~%int8 skill_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TutorialResult)))
  "Returns full string definition for message of type 'TutorialResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 ERROR = -1~%int8 SUCCESS = 0~%int8 FAIL = 1~%int8 skill_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TutorialResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TutorialResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TutorialResult
    (cl:cons ':skill_result (skill_result msg))
))
