// Auto-generated. Do not edit!

// (in-package exercise_skill.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ExerciseResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.skill_result = null;
    }
    else {
      if (initObj.hasOwnProperty('skill_result')) {
        this.skill_result = initObj.skill_result
      }
      else {
        this.skill_result = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ExerciseResult
    // Serialize message field [skill_result]
    bufferOffset = _serializer.int8(obj.skill_result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ExerciseResult
    let len;
    let data = new ExerciseResult(null);
    // Deserialize message field [skill_result]
    data.skill_result = _deserializer.int8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'exercise_skill/ExerciseResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4e5dc85de4836ff949b7a939d7ae0b33';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int8 ERROR = -1
    int8 SUCCESS = 0
    int8 FAIL = 1
    int8 skill_result
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ExerciseResult(null);
    if (msg.skill_result !== undefined) {
      resolved.skill_result = msg.skill_result;
    }
    else {
      resolved.skill_result = 0
    }

    return resolved;
    }
};

// Constants for message
ExerciseResult.Constants = {
  ERROR: -1,
  SUCCESS: 0,
  FAIL: 1,
}

module.exports = ExerciseResult;
