#!/bin/bash

#rostopic pub /alz/landmarks_topic hand_gesture_msgs/HandLandmarks '{landmarks: {number: 0, name: WRIST, coordinates: {0.0, 0.0}}, {number: 1, name: THUMB_MCP, coordinates: {0.0, 0.0}}}' -- -1
rostopic pub /alz/landmarks_topic hand_gesture_msgs/HandLandmarks '{landmarks: [{number: 0, name: WRIST, coordinates: [0.0, 0.0]},{number: 1, name: THUMB_CMC, coordinates: [0.0, 0.0]},{number: 2, name: THUMB_MCP, coordinates: [0.0, 0.0]},{number: 3, name: THUMB_IP, coordinates: [0.0, 0.0]},{number: 4, name: THUMB_TIP, coordinates: [0.0, 0.0]},{number: 5, name: INDEX_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 6, name: INDEX_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 7, name: INDEX_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 8, name: INDEX_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 9, name: MIDDLE_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 10, name: MIDDLE_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 11, name: MIDDLE_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 12, name: MIDDLE_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 13, name: RING_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 14, name: RING_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 15, name: RING_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 16, name: RING_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 17, name: PINKY_MCP, coordinates: [0.0, 0.0]},{number: 18, name: PINKY_PIP, coordinates: [0.0, 0.0]},{number: 19, name: PINKY_DIP, coordinates: [0.0, 0.0]},{number: 20, name: PINKY_TIP, coordinates: [0.0, 0.0]}]}' -1

rostopic pub /alz/landmarks_topic hand_gesture_msgs/HandLandmarks '{landmarks: [{number: 0, name: WRIST, coordinates: [0.0, 0.0]},{number: 1, name: THUMB_CMC, coordinates: [0.0, 0.0]},{number: 2, name: THUMB_MCP, coordinates: [0.0, 0.0]},{number: 3, name: THUMB_IP, coordinates: [0.0, 0.0]},{number: 4, name: THUMB_TIP, coordinates: [0.0, 0.0]},{number: 5, name: INDEX_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 6, name: INDEX_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 7, name: INDEX_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 8, name: INDEX_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 9, name: MIDDLE_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 10, name: MIDDLE_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 11, name: MIDDLE_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 12, name: MIDDLE_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 13, name: RING_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 14, name: RING_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 15, name: RING_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 16, name: RING_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 17, name: PINKY_MCP, coordinates: [0.0, 0.0]},{number: 18, name: PINKY_PIP, coordinates: [0.0, 0.0]},{number: 19, name: PINKY_DIP, coordinates: [0.0, 0.0]},{number: 20, name: PINKY_TIP, coordinates: [0.0, 0.0]}]}' -1

rostopic pub /alz/landmarks_topic hand_gesture_msgs/HandLandmarks '{landmarks: [{number: 0, name: WRIST, coordinates: [0.0, 0.0]},{number: 1, name: THUMB_CMC, coordinates: [0.0, 0.0]},{number: 2, name: THUMB_MCP, coordinates: [0.0, 0.0]},{number: 3, name: THUMB_IP, coordinates: [0.0, 0.0]},{number: 4, name: THUMB_TIP, coordinates: [0.0, 0.0]},{number: 5, name: INDEX_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 6, name: INDEX_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 7, name: INDEX_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 8, name: INDEX_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 9, name: MIDDLE_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 10, name: MIDDLE_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 11, name: MIDDLE_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 12, name: MIDDLE_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 13, name: RING_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 14, name: RING_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 15, name: RING_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 16, name: RING_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 17, name: PINKY_MCP, coordinates: [0.0, 0.0]},{number: 18, name: PINKY_PIP, coordinates: [0.0, 0.0]},{number: 19, name: PINKY_DIP, coordinates: [0.0, 0.0]},{number: 20, name: PINKY_TIP, coordinates: [0.0, 0.0]}]}' -1

rostopic pub /alz/landmarks_topic hand_gesture_msgs/HandLandmarks '{landmarks: [{number: 0, name: WRIST, coordinates: [0.0, 0.0]},{number: 1, name: THUMB_CMC, coordinates: [0.0, 0.0]},{number: 2, name: THUMB_MCP, coordinates: [0.0, 0.0]},{number: 3, name: THUMB_IP, coordinates: [0.0, 0.0]},{number: 4, name: THUMB_TIP, coordinates: [0.0, 0.0]},{number: 5, name: INDEX_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 6, name: INDEX_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 7, name: INDEX_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 8, name: INDEX_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 9, name: MIDDLE_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 10, name: MIDDLE_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 11, name: MIDDLE_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 12, name: MIDDLE_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 13, name: RING_FINGER_MCP, coordinates: [0.0, 0.0]},{number: 14, name: RING_FINGER_PIP, coordinates: [0.0, 0.0]},{number: 15, name: RING_FINGER_DIP, coordinates: [0.0, 0.0]},{number: 16, name: RING_FINGER_TIP, coordinates: [0.0, 0.0]},{number: 17, name: PINKY_MCP, coordinates: [0.0, 0.0]},{number: 18, name: PINKY_PIP, coordinates: [0.0, 0.0]},{number: 19, name: PINKY_DIP, coordinates: [0.0, 0.0]},{number: 20, name: PINKY_TIP, coordinates: [0.0, 0.0]}]}' -1
