// Generated by gencpp from file hand_gesture_msgs/HandLandmarks.msg
// DO NOT EDIT!


#ifndef HAND_GESTURE_MSGS_MESSAGE_HANDLANDMARKS_H
#define HAND_GESTURE_MSGS_MESSAGE_HANDLANDMARKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hand_gesture_msgs/HandLandmark.h>

namespace hand_gesture_msgs
{
template <class ContainerAllocator>
struct HandLandmarks_
{
  typedef HandLandmarks_<ContainerAllocator> Type;

  HandLandmarks_()
    : landmarks()  {
    }
  HandLandmarks_(const ContainerAllocator& _alloc)
    : landmarks(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::hand_gesture_msgs::HandLandmark_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hand_gesture_msgs::HandLandmark_<ContainerAllocator> >::other >  _landmarks_type;
  _landmarks_type landmarks;





  typedef boost::shared_ptr< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> const> ConstPtr;

}; // struct HandLandmarks_

typedef ::hand_gesture_msgs::HandLandmarks_<std::allocator<void> > HandLandmarks;

typedef boost::shared_ptr< ::hand_gesture_msgs::HandLandmarks > HandLandmarksPtr;
typedef boost::shared_ptr< ::hand_gesture_msgs::HandLandmarks const> HandLandmarksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_gesture_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hand_gesture_msgs': ['/home/haobing/catkin_ws/src/hand_gesture_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f0322f1ef8324746d3ce6a203bcab22";
  }

  static const char* value(const ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f0322f1ef832474ULL;
  static const uint64_t static_value2 = 0x6d3ce6a203bcab22ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_gesture_msgs/HandLandmarks";
  }

  static const char* value(const ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents a set of hand landmarks, each having two coordinates, a number and a name assigned to it (see README.md for more info)\n\
\n\
HandLandmark[] landmarks\n\
================================================================================\n\
MSG: hand_gesture_msgs/HandLandmark\n\
# This message represents a single hand landmark\n\
\n\
int32 number  # from 0 to 20\n\
string name  # see README.md for more info\n\
float32[] coordinates  # coordinates x and y\n\
";
  }

  static const char* value(const ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.landmarks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandLandmarks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_gesture_msgs::HandLandmarks_<ContainerAllocator>& v)
  {
    s << indent << "landmarks[]" << std::endl;
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      s << indent << "  landmarks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hand_gesture_msgs::HandLandmark_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_GESTURE_MSGS_MESSAGE_HANDLANDMARKS_H
