// Generated by gencpp from file tutorial_skill/TutorialAction.msg
// DO NOT EDIT!


#ifndef TUTORIAL_SKILL_MESSAGE_TUTORIALACTION_H
#define TUTORIAL_SKILL_MESSAGE_TUTORIALACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tutorial_skill/TutorialActionGoal.h>
#include <tutorial_skill/TutorialActionResult.h>
#include <tutorial_skill/TutorialActionFeedback.h>

namespace tutorial_skill
{
template <class ContainerAllocator>
struct TutorialAction_
{
  typedef TutorialAction_<ContainerAllocator> Type;

  TutorialAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  TutorialAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::tutorial_skill::TutorialActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::tutorial_skill::TutorialActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::tutorial_skill::TutorialActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::tutorial_skill::TutorialAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_skill::TutorialAction_<ContainerAllocator> const> ConstPtr;

}; // struct TutorialAction_

typedef ::tutorial_skill::TutorialAction_<std::allocator<void> > TutorialAction;

typedef boost::shared_ptr< ::tutorial_skill::TutorialAction > TutorialActionPtr;
typedef boost::shared_ptr< ::tutorial_skill::TutorialAction const> TutorialActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_skill::TutorialAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_skill::TutorialAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tutorial_skill

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tutorial_skill': ['/home/haobing/catkin_ws/devel/share/tutorial_skill/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'common_msgs': ['/home/haobing/catkin_ws/src/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_skill::TutorialAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_skill::TutorialAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_skill::TutorialAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_skill::TutorialAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_skill::TutorialAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_skill::TutorialAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_skill::TutorialAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "911c553667764f0cfe7e691fb192f50c";
  }

  static const char* value(const ::tutorial_skill::TutorialAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x911c553667764f0cULL;
  static const uint64_t static_value2 = 0xfe7e691fb192f50cULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_skill::TutorialAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_skill/TutorialAction";
  }

  static const char* value(const ::tutorial_skill::TutorialAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_skill::TutorialAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
TutorialActionGoal action_goal\n\
TutorialActionResult action_result\n\
TutorialActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: tutorial_skill/TutorialActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
TutorialGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: tutorial_skill/TutorialGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
uint8 max_time\n\
\n\
================================================================================\n\
MSG: tutorial_skill/TutorialActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
TutorialResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: tutorial_skill/TutorialResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int8 ERROR = -1\n\
int8 SUCCESS = 0\n\
int8 FAIL = 1\n\
int8 skill_result\n\
\n\
================================================================================\n\
MSG: tutorial_skill/TutorialActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
TutorialFeedback feedback\n\
\n\
================================================================================\n\
MSG: tutorial_skill/TutorialFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string app_status\n\
uint8 percentage_completed\n\
bool engagement\n\
common_msgs/KeyValuePair[] response_params\n\
\n\
\n\
================================================================================\n\
MSG: common_msgs/KeyValuePair\n\
#use standard header\n\
#Header header\n\
\n\
#string values for key and its value\n\
string key\n\
string value\n\
";
  }

  static const char* value(const ::tutorial_skill::TutorialAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_skill::TutorialAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TutorialAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_skill::TutorialAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_skill::TutorialAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::tutorial_skill::TutorialActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::tutorial_skill::TutorialActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::tutorial_skill::TutorialActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_SKILL_MESSAGE_TUTORIALACTION_H
